Fixed: AttributeError: 'MissingFunctionException' object has no attribute 'message' (#289)
* Update xlib.py

`MissingFunctionException` from `pyglet/gl/lib.py` (inherits`Exception`) does not have a `.message` attribute. Not sure if that's part of `BaseException`, but this caused runtime errors on xlib machines.

The specific error being:

```
AttributeError: 'MissingFunctionException' object has no attribute 'message'
```

* Forgot to cast the error message just in case.

I think this is taken care of further down the line. But just in case. Sourced from: https://github.com/pyglet/pyglet/blob/d563b7a001506758a77fde035c22c786476d0093/pyglet/image/codecs/wic.py#L289