Update xlib.py
`MissingFunctionException` from `pyglet/gl/lib.py` (inherits`Exception`) does not have a `.message` attribute. Not sure if that's part of `BaseException`, but this caused runtime errors on xlib machines.

The specific error being:

```
AttributeError: 'MissingFunctionException' object has no attribute 'message'
```